// Official list of Colombo Municipal Council wards, per the Sri Lanka
// Election Commission's local authority ward register (elections.gov.lk).
const List<String> colomboWards = [
  'Sammanthranapura',
  'Mattakkuliya',
  'Modara',
  'Mahawatta',
  'Aluth Mawatha',
  'Lunupokuna',
  'Kotahena West',
  'Kotahena East',
  'Bloemendhal',
  'Grandpass North',
  'Navagampura',
  'Dematagoda',
  'Maligawatta East',
  'Grandpass South',
  'Khettarama',
  'New Bazaar',
  'Masangasweediya',
  'Jintupitiya',
  'Kochchikade',
  'Fort',
  'Kochchikade South',
  'Hultsdorf West',
  'Hultsdorf East',
  'Keselwatta',
  'Panchikawatta',
  'Maligawatta West',
  'Maradana',
  'Kuppiyawatta East',
  'Wanathamulla',
  'Borella North',
  'Kuppiyawatta West',
  'Hunupitiya',
  'Wekanda',
  'Kollupitiya',
  'Bambalapitiya',
  'Cinnamon Gardens',
  'Borella South',
  'Gothamipura',
  'Narahenpita',
  'Thimbirigasyaya',
  'Havelock Town',
  'Kirula',
  'Kirulapana',
  'Pamankada East',
  'Pamankada West',
  'Wellawatta North',
  'Wellawatta South',
];
