// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnNy4xuav-Gj7-TB6LJgy6SObcENaA4nM',
    appId: '1:220984755302:web:edc3bfa7c02dd4034b99a7',
    messagingSenderId: '220984755302',
    projectId: 'r26-it-126-waste-app',
    authDomain: 'r26-it-126-waste-app.firebaseapp.com',
    storageBucket: 'r26-it-126-waste-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4T-hyua1sVaSl9GorLUn2v73x2_i1mMc',
    appId: '1:220984755302:android:7abd1be9b41ab39e4b99a7',
    messagingSenderId: '220984755302',
    projectId: 'r26-it-126-waste-app',
    storageBucket: 'r26-it-126-waste-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZPIcKHF7Q-zG4_Fv_6FMH-Y0NhGT_WUY',
    appId: '1:220984755302:ios:f49efecac74e80fc4b99a7',
    messagingSenderId: '220984755302',
    projectId: 'r26-it-126-waste-app',
    storageBucket: 'r26-it-126-waste-app.firebasestorage.app',
    iosBundleId: 'com.r26it126.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZPIcKHF7Q-zG4_Fv_6FMH-Y0NhGT_WUY',
    appId: '1:220984755302:ios:f49efecac74e80fc4b99a7',
    messagingSenderId: '220984755302',
    projectId: 'r26-it-126-waste-app',
    storageBucket: 'r26-it-126-waste-app.firebasestorage.app',
    iosBundleId: 'com.r26it126.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnNy4xuav-Gj7-TB6LJgy6SObcENaA4nM',
    appId: '1:220984755302:web:d1abbd3229d4ff974b99a7',
    messagingSenderId: '220984755302',
    projectId: 'r26-it-126-waste-app',
    authDomain: 'r26-it-126-waste-app.firebaseapp.com',
    storageBucket: 'r26-it-126-waste-app.firebasestorage.app',
  );
}
